#!/usr/bin/env node
// Generate a self-hosted stack's .env, including the two JWTs the stack needs.
//
// Why this is a script and not a documented "paste a key here": the anon and service_role keys
// ARE jwts signed with the stack's own JWT_SECRET, carrying a `role` claim that is what PostgREST
// and storage-api authorise against. A hand-copied key from elsewhere would not verify against
// this secret, and a placeholder would let the stack boot while every request 401s — a failure
// that looks like a broken client rather than a broken key.
//
// Writing this also removes a limitation the hosted path had: the seed verifier could not mint
// the four BRITELINK_TEST_*_JWT values because only Supabase Auth could sign them. Here the
// signing secret is local, so staging tokens are mintable rather than hand-fed.
//
// Usage:  node scripts/selfhosted-staging/gen-env.mjs [--force]
//         node scripts/selfhosted-staging/gen-env.mjs --out /opt/britelink-production/supabase/selfhosted/.env \
//              --stack-name britelink-production --gateway-port 8098 \
//              --public-url https://britelink-api.ashbi.ca
//
// Refuses to overwrite an existing .env without --force, so a live secret is never silently
// rotated out from under a running stack. That guard matters more, not less, for production:
// regenerating a live stack's JWT_SECRET invalidates every key and every session at once.
//
// With no flags this writes the staging .env exactly as it always has. The defaults are load
// bearing — staging's running stack was created from them.

import { createHmac, randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  if (i === -1) return fallback;
  const value = process.argv[i + 1];
  if (value === undefined || value.startsWith("--")) {
    console.error(`--${name} needs a value`);
    process.exit(1);
  }
  return value;
}

const force = process.argv.includes("--force");
const stackName = arg("stack-name", "britelink-staging");
const gatewayPort = arg("gateway-port", "8099");
const publicUrl = arg("public-url", `http://127.0.0.1:${gatewayPort}`);
// What GoTrue puts in magic-link redirects and what the SPA is served from. They are the same
// origin in staging (the loopback gateway) and necessarily different in production (an HTTPS API
// host beside an HTTPS site host), which is why this is its own value rather than reused.
const siteUrl = arg("site-url", publicUrl);
const target = arg("out", join(repo, "supabase", "selfhosted", ".env"));

// Derived, so staging's `iss` is character-for-character what it has always been.
const iss = `supabase-${stackName.replace(/^britelink-/, "")}`;
const isStaging = stackName === "britelink-staging";

if (existsSync(target) && !force) {
  console.error(`refusing to overwrite ${target} (pass --force to rotate the secrets)`);
  process.exit(1);
}

// Supabase requires a JWT secret of at least 32 characters; 48 bytes of base64 is comfortably past
// it and costs nothing.
const b64url = (buf) =>
  Buffer.from(buf).toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");

const jwtSecret = b64url(randomBytes(48));
const postgresPassword = b64url(randomBytes(24));

// The two standard Supabase roles. `aud` and `iss` match what PostgREST expects, and `exp` is far
// out because these are the stack's permanent keys, not session tokens — the short-lived session
// tokens are the BRITELINK_TEST_*_JWT ones minted separately.
function key(role) {
  const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = b64url(
    JSON.stringify({
      role,
      iss,
      iat: Math.floor(Date.now() / 1000),
      exp: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365 * 10,
    }),
  );
  const signature = b64url(createHmac("sha256", jwtSecret).update(`${header}.${payload}`).digest());
  return `${header}.${payload}.${signature}`;
}

const banner = isStaging
  ? `# GENERATED by scripts/selfhosted-staging/gen-env.mjs — do not commit.
# Synthetic staging only. Every value here is disposable; none of it is a production credential.`
  : `# GENERATED by scripts/selfhosted-staging/gen-env.mjs — do not commit.
# PRODUCTION. These are live credentials: JWT_SECRET signs every session token this stack issues,
# and SERVICE_KEY bypasses row-level security entirely. Rotating JWT_SECRET here invalidates every
# key and every signed-in session at once, so it is not a routine action.`;

const env = `${banner}
# Names this stack. Compose namespaces the network and volumes under it, which is what keeps
# production's data physically separate from staging's. COMPOSE_PROJECT_NAME repeats it so a
# command that misses the file's variable still cannot resolve to the wrong project.
STACK_NAME=${stackName}
COMPOSE_PROJECT_NAME=${stackName}
POSTGRES_PASSWORD=${postgresPassword}
JWT_SECRET=${jwtSecret}
ANON_KEY=${key("anon")}
SERVICE_KEY=${key("service_role")}
# The gateway listens on 127.0.0.1 only. Change the port here if it is taken on the host.
GATEWAY_PORT=${gatewayPort}
# PUBLIC_URL is the API origin the services call themselves; SITE_URL is the SPA origin GoTrue
# will send magic-link redirects to. Staging shares one origin; production does not.
PUBLIC_URL=${publicUrl}
SITE_URL=${siteUrl}
`;

writeFileSync(target, env, { mode: 0o600 });
console.log(`wrote ${target}`);
console.log(`  STACK_NAME         ${stackName}`);
console.log("  POSTGRES_PASSWORD  (random)");
console.log("  JWT_SECRET         (random, 48 bytes)");
console.log(`  ANON_KEY           (HS256, role=anon, iss=${iss})`);
console.log("  SERVICE_KEY        (HS256, role=service_role)");
console.log(`  GATEWAY_PORT=${gatewayPort}  PUBLIC_URL=${publicUrl}  SITE_URL=${siteUrl}`);
