#!/usr/bin/env node
// Generate the self-hosted staging stack's .env, including the two JWTs the stack needs.
//
// Why this is a script and not a documented "paste a key here": the anon and service_role keys
// ARE jwts signed with the stack's own JWT_SECRET, carrying a `role` claim that is what PostgREST
// and storage-api authorise against. A hand-copied key from elsewhere would not verify against
// this secret, and a placeholder would let the stack boot while every request 401s — a failure
// that looks like a broken client rather than a broken key.
//
// Writing this also removes a limitation the hosted path had: the seed verifier could not mint
// the four BRITELINK_TEST_*_JWT values because only Supabase Auth could sign them. Here the
// signing secret is local, so staging tokens are mintable rather than hand-fed.
//
// Usage:  node scripts/selfhosted-staging/gen-env.mjs [--force]
// Refuses to overwrite an existing .env without --force, so a live staging secret is never
// silently rotated out from under a running stack.

import { createHmac, randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const target = join(repo, "supabase", "selfhosted", ".env");

const force = process.argv.includes("--force");
if (existsSync(target) && !force) {
  console.error(`refusing to overwrite ${target} (pass --force to rotate the secrets)`);
  process.exit(1);
}

// Supabase requires a JWT secret of at least 32 characters; 48 bytes of base64 is comfortably past
// it and costs nothing.
const b64url = (buf) =>
  Buffer.from(buf).toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");

const jwtSecret = b64url(randomBytes(48));
const postgresPassword = b64url(randomBytes(24));

// The two standard Supabase roles. `aud` and `iss` match what PostgREST expects, and `exp` is far
// out because these are the stack's permanent keys, not session tokens — the short-lived session
// tokens are the BRITELINK_TEST_*_JWT ones minted separately.
function key(role) {
  const header = b64url(JSON.stringify({ alg: "HS256", typ: "JWT" }));
  const payload = b64url(
    JSON.stringify({
      role,
      iss: "supabase-staging",
      iat: Math.floor(Date.now() / 1000),
      exp: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365 * 10,
    }),
  );
  const signature = b64url(createHmac("sha256", jwtSecret).update(`${header}.${payload}`).digest());
  return `${header}.${payload}.${signature}`;
}

const env = `# GENERATED by scripts/selfhosted-staging/gen-env.mjs — do not commit.
# Synthetic staging only. Every value here is disposable; none of it is a production credential.
POSTGRES_PASSWORD=${postgresPassword}
JWT_SECRET=${jwtSecret}
ANON_KEY=${key("anon")}
SERVICE_KEY=${key("service_role")}
# The gateway listens on 127.0.0.1 only. Change the port here if 8099 is taken on the host.
GATEWAY_PORT=8099
PUBLIC_URL=http://127.0.0.1:8099
`;

writeFileSync(target, env, { mode: 0o600 });
console.log(`wrote ${target}`);
console.log("  POSTGRES_PASSWORD  (random)");
console.log("  JWT_SECRET         (random, 48 bytes)");
console.log("  ANON_KEY           (HS256, role=anon)");
console.log("  SERVICE_KEY        (HS256, role=service_role)");
console.log("  GATEWAY_PORT=8099  PUBLIC_URL=http://127.0.0.1:8099");
