import { useCallback, useEffect, useState } from "react";
import { classifyOperationError } from "./operation-state.js";
import { createHouseholdExportFile, deliveryPresentation, newestByCreatedAt } from "./guardian-service.js";
import { loadPrivacyWorkspaceData } from "./privacy-workspace.js";

const IDLE={status:"idle",message:"",canRetry:false};
function failure(error,action){const status=classifyOperationError(error);return{status,message:status==="offline"?`${action} is unavailable while you are offline.`:status==="session_expired"?"Your session expired. Sign in again before continuing.":status==="conflict"?`${action} conflicted with a newer change. Reload before trying again.`:error.message,canRetry:status==="offline"||status==="error"}}
function Notice({state}){if(!state.message)return null;const failed=["offline","conflict","session_expired","error"].includes(state.status);return <div className={`service-notice ${failed?"failure":"success"}`} role={failed?"alert":"status"}><span>{state.message}</span>{state.canRetry&&state.onRetry?<button type="button" className="ghost" onClick={state.onRetry}>{state.retryLabel??"Retry refresh"}</button>:null}</div>}

export function AuthenticatedServicePrivacy({householdId,learner,serviceCase,userId,userEmail,repository,refreshKey=0}){
  const [data,setData]=useState({status:"loading",consents:[],deliveries:[],revisions:[],privacyRequests:[],warnings:[],error:null});const [operation,setOperation]=useState(IDLE);const [revisionReason,setRevisionReason]=useState("");const [deletionReason,setDeletionReason]=useState("");const [deleteConfirmed,setDeleteConfirmed]=useState(false);const [withdrawConfirmed,setWithdrawConfirmed]=useState(false);
  const load=useCallback(async()=>{setData(previous=>({...previous,status:"loading",error:null}));try{const loaded=await loadPrivacyWorkspaceData(repository,{householdId,learnerId:learner.id,userId,caseId:serviceCase?.id});setData({status:"success",...loaded,error:null});return loaded}catch(error){setData(previous=>({...previous,status:"error",error:error.message}));throw error}},[householdId,learner.id,repository,serviceCase,userId,refreshKey]);
  useEffect(()=>{load().catch(()=>{})},[load]);
  const finishWrite=async message=>{try{const refreshed=await load();setOperation({status:"success",message:refreshed.warnings.length?`${message} Some panels could not refresh; retry before relying on their status.`:message,canRetry:false})}catch{setOperation({status:"success",message:`${message} The latest records could not be refreshed; use Retry refresh before taking another action.`,canRetry:true,onRetry:()=>load().catch(()=>{})})}};
  const needsFreshSignIn=error=>/recent authentication required/i.test(error?.message??"");
  const requestFreshSignIn=async()=>{setOperation({status:"loading",message:"Sending a fresh secure sign-in link…",canRetry:false});try{await repository.requestFreshSignIn(userEmail,globalThis.location?.origin);setOperation({status:"success",message:"Fresh sign-in link sent. Open it in this browser, return here, and repeat the export or deletion request within 10 minutes.",canRetry:false})}catch(error){setOperation(failure(error,"Fresh sign-in link"))}};
  const delivery=newestByCreatedAt(data.deliveries??[]);const deliveryView=deliveryPresentation(delivery);const openDeletion=(data.privacyRequests??[]).find(item=>item.kind==="deletion"&&["pending","verified","scheduled"].includes(item.status));
  const acknowledge=async()=>{setOperation({status:"loading",message:"Recording acknowledgement…",canRetry:false});try{await repository.acknowledgeDelivery(householdId,delivery.id);await finishWrite("Plan delivery acknowledged. Any included revision can now be requested.")}catch(error){setOperation(failure(error,"Delivery acknowledgement"))}};
  const requestRevision=async(event)=>{event.preventDefault();setOperation({status:"loading",message:"Submitting revision request…",canRetry:false});try{const result=await repository.requestRevision({householdId,caseId:serviceCase.id,reason:revisionReason});setRevisionReason("");await finishWrite(`Revision request ${result?.entitlement_index??""} submitted. ${result?.remaining_revisions??0} included revision(s) remain.`)}catch(error){setOperation(failure(error,"Revision request"))}};
  const exportData=async()=>{setOperation({status:"loading",message:"Preparing your household export…",canRetry:false});try{const payload=await repository.exportHousehold(householdId);const file=createHouseholdExportFile(payload);const url=URL.createObjectURL(new Blob([file.contents],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=file.filename;anchor.click();URL.revokeObjectURL(url);setOperation({status:"success",message:"Household export downloaded as JSON on this device.",canRetry:false})}catch(error){setOperation(needsFreshSignIn(error)?{status:"error",message:"For your protection, exporting household data requires a fresh sign-in from the last 10 minutes.",canRetry:true,onRetry:requestFreshSignIn,retryLabel:"Send fresh sign-in link"}:failure(error,"Household export"))}};
  const withdraw=async()=>{const consent=data.consents[0];setOperation({status:"loading",message:"Withdrawing consent and pausing service…",canRetry:false});try{await repository.withdrawConsent(householdId,consent.id);setWithdrawConfirmed(false);await finishWrite("Consent withdrawn. Active service is on hold and educator access to this intake has ended unless another active consent exists.")}catch(error){setOperation(failure(error,"Consent withdrawal"))}};
  const requestDeletion=async(event)=>{event.preventDefault();setOperation({status:"loading",message:"Submitting deletion request…",canRetry:false});try{const request=await repository.requestDeletion({householdId,reason:deletionReason,confirmed:deleteConfirmed});setDeleteConfirmed(false);await finishWrite(`Deletion request is ${request?.request_status??"pending"}. No data has been deleted; BriteLink must verify identity, retention exceptions, and scope.`)}catch(error){setOperation(needsFreshSignIn(error)?{status:"error",message:"For your protection, household deletion requests require a fresh sign-in from the last 10 minutes.",canRetry:true,onRetry:requestFreshSignIn,retryLabel:"Send fresh sign-in link"}:failure(error,"Deletion request"))}};
  return <section className="live-service" aria-labelledby="service-heading"><header><span className="eyebrow">Service and privacy</span><h2 id="service-heading">Delivery, revisions, and your data</h2><p>These actions stay inside your household. Export and deletion need a recent sign-in and never happen from this page alone.</p></header>{data.status==="loading"?<p className="plan-state" role="status">Loading service and privacy records…</p>:data.status==="error"?<div className="plan-state"><p role="alert">{data.error}</p><button className="ghost" onClick={()=>load().catch(()=>{})}>Try again</button></div>:<><>{data.warnings.length?<div className="live-operation failure" role="alert"><strong>Some service or privacy records are temporarily unavailable.</strong><span>Affected panels: {data.warnings.map(item=>item.panel).join(", ")}. Empty results in those panels are not authoritative.</span><button type="button" className="ghost" onClick={()=>load().catch(()=>{})}>Retry affected panels</button></div>:null}</>
    <div className="service-group"><h3>Your plan</h3><p>Acknowledge a delivered plan or request an included revision. Status here is only what BriteLink has recorded for this household.</p><div className="service-grid">
    <article><h3>Plan delivery</h3>{!serviceCase?<p>No service case is connected to this learner.</p>:!delivery?<p>{deliveryView.message}</p>:<><dl><div><dt>Status</dt><dd>{deliveryView.label}</dd></div><div><dt>Version</dt><dd>{delivery.plan_version}</dd></div><div><dt>Sent</dt><dd>{delivery.sent_at?new Date(delivery.sent_at).toLocaleString():"Not sent"}</dd></div></dl><p className={`service-delivery-state ${deliveryView.tone}`} role={deliveryView.tone==="failure"?"alert":"status"}>{deliveryView.message}</p>{deliveryView.canAcknowledge?<button className="primary" disabled={operation.status==="loading"} onClick={acknowledge}>I received this plan</button>:null}</>}</article>
    <article><h3>Included revisions</h3>{!serviceCase?<p>A service case is required.</p>:<><div className="service-history">{data.revisions.length?data.revisions.map(item=><p key={item.id}><strong>{item.status}</strong><span>{item.reason}</span></p>):<p>No revisions requested.</p>}</div><form onSubmit={requestRevision}><label>What should change?<textarea required maxLength="2000" value={revisionReason} onChange={event=>setRevisionReason(event.target.value)} /></label><button className="primary" disabled={operation.status==="loading"}>Request included revision</button></form></>}</article>
    </div></div>
    <div className="service-group"><h3>Your data</h3><p>Export, consent, and deletion are household-wide. Use them only when you intend the change. BriteLink will not erase data from a request on this page.</p><div className="service-grid">
    <article><h3>Portable household export</h3><p>Download the household’s BriteLink records as structured JSON. The file may contain sensitive learner information; store it securely.</p><button className="ghost" disabled={operation.status==="loading"} onClick={exportData}>Download my data</button></article>
    <article><h3>Consent</h3>{data.consents.length?<><p>Active notice: {data.consents[0].notice_version}</p><label className="service-confirm"><input type="checkbox" checked={withdrawConfirmed} onChange={event=>setWithdrawConfirmed(event.target.checked)} /> I understand this pauses active service and ends educator access when no other active consent exists.</label><button className="danger" disabled={!withdrawConfirmed||operation.status==="loading"} onClick={withdraw}>Withdraw my active consent</button></>:<p>No active consent attributed to this signed-in guardian.</p>}</article>
    <article className="service-delete"><h3>Request household deletion</h3>{openDeletion?<p className="service-complete">A deletion request is already {openDeletion.status}. No duplicate request is needed.</p>:<form onSubmit={requestDeletion}><p>This creates a review request; it does not immediately erase records. BriteLink must verify identity, other guardians, legal/financial retention, backups, and deletion scope.</p><label>Reason <span>(optional)</span><textarea maxLength="1000" value={deletionReason} onChange={event=>setDeletionReason(event.target.value)} /></label><label className="service-confirm"><input type="checkbox" checked={deleteConfirmed} onChange={event=>setDeleteConfirmed(event.target.checked)} /> I understand this is a household-wide request subject to identity and retention review.</label><button className="danger" disabled={!deleteConfirmed||operation.status==="loading"}>Request household deletion</button></form>}</article>
    </div></div></>}<Notice state={operation}/></section>;
}
