import React from "react";
import { createRoot } from "react-dom/client";
import { Workspace } from "/src/AuthenticatedApp.jsx";
import "/src/styles.css";

const now="2026-08-28T15:00:00Z";
const qaState={calls:[],activities:[],profiles:[],consents:[],cases:[{id:"case-a",learner_id:"learner-a",package_code:"complete",status:"delivered"}],deliveries:[{id:"delivery-a",case_id:"case-a",plan_id:"plan-a",plan_version:2,channel:"secure_portal",status:"sent",attempt_count:1,sent_at:now,acknowledged_at:null,created_at:now}],revisions:[],privacyRequests:[],messages:[{id:"message-educator",sender_user_id:"educator-a",kind:"general",body:"I reviewed the reading activity and added a phonics prompt.",created_at:now,case_message_reads:[]}]};
globalThis.qaState=qaState;
function failPrivacyRefresh(){if((globalThis.qaFailPrivacyReads??0)>0){globalThis.qaFailPrivacyReads-=1;throw new Error("Synthetic privacy refresh outage")}}

const repository={
  async listMemberships(){qaState.calls.push(["listMemberships"]);return[{household_id:"household-a",role:"guardian",households:{id:"household-a",display_name:"QA Family"}}]},
  async listLearners(householdId){qaState.calls.push(["listLearners",householdId]);return[{id:"learner-a",preferred_name:"Maya",grade_label:"Grade 4"},{id:"learner-b",preferred_name:"Noah",grade_label:"Grade 2"}]},
  async listCases(householdId){qaState.calls.push(["listCases",householdId]);return qaState.cases},
  async loadLatestProfile(householdId,learnerId){qaState.calls.push(["loadLatestProfile",householdId,learnerId]);return qaState.profiles.filter(item=>item.learner_id===learnerId).sort((a,b)=>b.version-a.version)[0]??null},
  async submitGuardianIntake(input){qaState.calls.push(["submitGuardianIntake",input.householdId,input.learnerId,input.noticeVersion]);const version=qaState.profiles.filter(item=>item.learner_id===input.learnerId).length+1;const consentId=`consent-${input.learnerId}-${version}`;qaState.profiles.push({id:`profile-${input.learnerId}-${version}`,learner_id:input.learnerId,version,planning_context:{subjects:input.subjects,priorAttainment:input.priorAttainment,strengthsInterests:input.strengthsInterests,goals:input.goals,learningSupports:input.learningSupports,language:input.language,weeklySchedule:input.weeklySchedule,caregiverAvailability:input.caregiverAvailability,deviceAccess:input.deviceAccess,resourceBudget:input.resourceBudget,contentConstraints:input.contentConstraints,accessibilityNeeds:input.accessibilityNeeds,planningStructure:input.planningStructure},submitted_at:now});qaState.consents.push({id:consentId,learner_id:input.learnerId,guardian_user_id:"guardian-a",notice_version:input.noticeVersion,purposes:["personalized_learning_plan"],consented_at:now});return{profile_version:version,consent_id:consentId}},
  async listActiveConsents(householdId,learnerId,userId){qaState.calls.push(["listActiveConsents",householdId,learnerId,userId]);failPrivacyRefresh();return qaState.consents.filter(item=>item.learner_id===learnerId&&item.guardian_user_id===userId&&!item.withdrawn_at)},
  async withdrawConsent(householdId,consentId){qaState.calls.push(["withdrawConsent",householdId,consentId]);const consent=qaState.consents.find(item=>item.id===consentId);consent.withdrawn_at=now;qaState.cases.forEach(item=>{if(item.learner_id===consent.learner_id)item.status="on_hold"});return now},
  async loadPublishedPlans(householdId,learnerId){qaState.calls.push(["loadPublishedPlans",householdId,learnerId]);if(learnerId==="learner-a"&&globalThis.qaDelayLearnerA)await new Promise(resolve=>setTimeout(resolve,400));if(learnerId!=="learner-a")return[];return[{id:"plan-a",version:2,status:"published",plan_weeks:[{id:"week-1",week_number:1,theme:"Curiosity and confidence",plan_days:[{id:"day-1",day_number:1,planned_date:"2026-09-01",lessons:[{id:"lesson-a",position:1,subject:"Language",title:"Build a sound map",objective:"Connect sounds to familiar words.",instructions:["Choose five familiar words.","Sort them by opening sound."],materials:["Paper","Pencil"],accommodations:["Read each instruction aloud."],adult_help_minutes:10,resources:[{id:"resource-a",title:"Printable sound cards",requirement:"optional",access_type:"free",estimated_cost_cents:0,region:"Canada",url:"https://example.test/sound-cards"}]},{id:"lesson-b",position:2,subject:"Math",title:"Count a collection",objective:"Group objects and explain the strategy.",instructions:["Choose a small collection.","Make equal groups."],materials:["Household objects"],accommodations:[],adult_help_minutes:5,estimated_minutes:15,help_level:"independent",needs_screen:false,resources:[]}]}]}]}]},
  async listLessonActivities(householdId,learnerId){qaState.calls.push(["listLessonActivities",householdId,learnerId]);return qaState.activities.filter(item=>item.learner_id===learnerId)},
  async listLearningCaptures(householdId,learnerId){qaState.calls.push(["listLearningCaptures",householdId,learnerId]);return(qaState.captures??[]).filter(item=>item.learner_id===learnerId&&!item.removed_at).sort((a,b)=>b.captured_on.localeCompare(a.captured_on))},recordLearningCapture(input){qaState.calls.push(["recordLearningCapture",input.householdId,input.learnerId]);const row={id:`capture-${(qaState.captures??[]).length+1}`,learner_id:input.learnerId,captured_on:input.capturedOn,kind:input.kind,subjects:[...input.subjects],note:input.note.trim(),created_at:now};(qaState.captures??=[]).push(row);return{capture_id:row.id}},removeLearningCapture(input){qaState.calls.push(["removeLearningCapture",input.householdId,input.captureId]);const row=(qaState.captures??[]).find(item=>item.id===input.captureId);if(row)row.removed_at=now;return now},setPlanSchedule(input){qaState.calls.push(["setPlanSchedule",input.householdId,input.planId]);if(globalThis.qaFailCalendarOnce){globalThis.qaFailCalendarOnce=false;throw new Error("Save your calendar: temporarily unavailable")}const row={plan_id:input.planId,start_date:input.startDate,school_days:[...input.schoolDays],days_off:[...(input.daysOff??[])],updated_at:now};qaState.schedule=row;return row},saveLessonActivity(input){qaState.calls.push(["saveLessonActivity",input.householdId,input.learnerId,input.lessonId]);if(globalThis.qaFailLessonSaveOnce){globalThis.qaFailLessonSaveOnce=false;throw new Error("Save lesson activity: temporarily unavailable")}const saved={id:"activity-a",lesson_id:input.lessonId,learner_id:input.learnerId,status:input.status,caregiver_note:input.note,schedule_reason:input.scheduleReason||null,scheduled_for:input.scheduledFor||null,updated_at:now};qaState.activities=qaState.activities.filter(item=>!(item.learner_id===input.learnerId&&item.lesson_id===input.lessonId)).concat(saved);return saved},
  async listMessages(householdId,caseId){qaState.calls.push(["listMessages",householdId,caseId]);return qaState.messages},
  async sendMessage(input){qaState.calls.push(["sendMessage",input.householdId,input.caseId,input.userId]);const saved={id:`message-${qaState.messages.length+1}`,sender_user_id:input.userId,kind:"general",body:input.body,created_at:now,case_message_reads:[],case_attachments:[]};qaState.messages.push(saved);return saved},
  async uploadMessageAttachment(input){qaState.calls.push(["uploadMessageAttachment",input.householdId,input.messageId]);const saved={id:`attachment-${input.messageId}`,file_name:input.file.name,mime_type:input.file.type,size_bytes:input.file.size,status:globalThis.qaFailNextAttachment?"upload_failed":"pending_scan",object_path:`${input.householdId}/case-a/${input.messageId}/attachment-a`};qaState.messages.find(item=>item.id===input.messageId).case_attachments.push(saved);if(globalThis.qaFailNextAttachment){globalThis.qaFailNextAttachment=false;const error=new Error("Synthetic upload interruption");error.attachmentRetry={attachmentId:saved.id,file:input.file};throw error}return saved},
  async retryMessageAttachmentUpload(input){qaState.calls.push(["retryMessageAttachmentUpload",input.householdId,input.attachmentId]);const attachment=qaState.messages.flatMap(item=>item.case_attachments??[]).find(item=>item.id===input.attachmentId);if(!attachment)throw new Error("Attachment not found");attachment.status="pending_scan";return attachment},
  async createAttachmentDownloadUrl(){throw new Error("Pending attachment cannot be downloaded")},
  async markMessageRead(input){qaState.calls.push(["markMessageRead",input.householdId,input.messageId,input.userId]);return{message_id:input.messageId,user_id:input.userId,read_at:now}},
  async listDeliveries(householdId,caseId){qaState.calls.push(["listDeliveries",householdId,caseId]);failPrivacyRefresh();return qaState.deliveries.filter(item=>item.case_id===caseId)},
  async acknowledgeDelivery(householdId,deliveryId){qaState.calls.push(["acknowledgeDelivery",householdId,deliveryId]);const item=qaState.deliveries.find(entry=>entry.id===deliveryId);item.status="acknowledged";item.acknowledged_at=now;qaState.cases.find(entry=>entry.id===item.case_id).status="acknowledged";return{delivery_id:deliveryId,case_id:item.case_id,acknowledged_at:now}},
  async listRevisions(householdId,caseId){qaState.calls.push(["listRevisions",householdId,caseId]);failPrivacyRefresh();return qaState.revisions.filter(item=>item.case_id===caseId)},
  async requestRevision(input){qaState.calls.push(["requestRevision",input.householdId,input.caseId]);const item={id:"revision-a",case_id:input.caseId,reason:input.reason,entitlement_index:1,status:"requested",created_at:now};qaState.revisions.push(item);qaState.cases.find(entry=>entry.id===input.caseId).status="revision_requested";return{revision_id:item.id,entitlement_index:1,remaining_revisions:0}},
  async exportHousehold(householdId){qaState.calls.push(["exportHousehold",householdId]);if(globalThis.qaRejectSensitiveOnce){globalThis.qaRejectSensitiveOnce=false;throw new Error("Export household: recent authentication required")}return{exportedAt:now,household:{id:householdId,display_name:"QA Family"},learners:[{id:"learner-a"}],profiles:qaState.profiles,consents:qaState.consents,cases:qaState.cases,plans:[],lessonActivities:qaState.activities,messages:qaState.messages,deliveries:qaState.deliveries,revisions:qaState.revisions,privacyRequests:qaState.privacyRequests}},
  async requestFreshSignIn(email,redirectTo){qaState.calls.push(["requestFreshSignIn",email,redirectTo]);return{}},
  async listPrivacyRequests(householdId){qaState.calls.push(["listPrivacyRequests",householdId]);failPrivacyRefresh();return qaState.privacyRequests},
  async requestDeletion(input){qaState.calls.push(["requestDeletion",input.householdId]);const existing=qaState.privacyRequests.find(item=>["pending","verified","scheduled"].includes(item.status));if(existing)return{request_id:existing.id,request_status:existing.status,created_at:existing.created_at};const item={id:"privacy-a",kind:"deletion",status:"pending",reason:input.reason,created_at:now};qaState.privacyRequests.push(item);return{request_id:item.id,request_status:item.status,created_at:item.created_at}},
  async signOut(){qaState.calls.push(["signOut"])}
};

createRoot(document.getElementById("root")).render(<Workspace repository={repository} session={{user:{id:"guardian-a",email:"guardian@example.ca"}}} privacyNoticeVersion="qa-notice-v1" inactivityMs={globalThis.qaInactivityMs}/>);
